to-edictor:
	edictor wordlist --name=girardprototakanan --data=../cldf/cldf-metadata.json --addon="cognacy:cogid,source:source,protoset:protoset,conceptinsource:conceptinsource,UncertainCognacy:uncertaincognacy"
